#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-List-SomeUtils-XS
Version  : 0.52
Release  : 3
URL      : http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/List-SomeUtils-XS-0.52.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/List-SomeUtils-XS-0.52.tar.gz
Summary  : 'XS implementation for List::SomeUtils'
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-List-SomeUtils-XS-lib
Requires: perl-List-SomeUtils-XS-doc
BuildRequires : perl(Test::Warnings)

%description
# NAME
List::SomeUtils::XS - XS implementation for List::SomeUtils
# VERSION
version 0.52

%package doc
Summary: doc components for the perl-List-SomeUtils-XS package.
Group: Documentation

%description doc
doc components for the perl-List-SomeUtils-XS package.


%package lib
Summary: lib components for the perl-List-SomeUtils-XS package.
Group: Libraries

%description lib
lib components for the perl-List-SomeUtils-XS package.


%prep
%setup -q -n List-SomeUtils-XS-0.52

%build
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.24.0/x86_64-linux-thread-multi/List/SomeUtils/XS.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.24.0/x86_64-linux-thread-multi/auto/List/SomeUtils/XS/XS.so
